USE BDEX5_EVENTOS;

#1
SELECT
E.NOME_EVENTO EVENTO,
GROUP_CONCAT(CONCAT(
A.NOME_ATV," ",
A.DATA_ATV," ",
A.HORA_ATV)) ATIVIDADE
FROM ATIVIDADES A
INNER JOIN EVENTOS E ON A.EVENTO_ATV =
E.ID_EVENTO
GROUP BY EVENTO;

#2
SELECT
PA.INSCRICAO,
P.NOME,
A.NOME_ATV AS NOME_ATIVIDADE
FROM PARTICIPANTES AS P
LEFT JOIN PARTICIPANTE_ATIVIDADE AS PA
ON P.CPF = PA.CPF
LEFT JOIN ATIVIDADES AS A
ON PA.ATIVIDADE = A.ID_ATIVIDADE;

#3
SELECT E.NOME_EVENTO, L.NOME AS LOCAL
FROM EVENTOS AS E
RIGHT JOIN LOCAIS AS L
ON E.LOCAL_EVENTO = L.ID_LOCAL;



