USE BDEX3_REDESOCIAL;

#1
SELECT * FROM USUARIOS;

#2
SELECT NOME_USUARIO,SOBRENOME,EMAIL
FROM USUARIOS;
 
 #3
 SELECT NOME_GRUPO,DESCRICAO FROM GRUPOS;
 
 #4
 SELECT P.ID_POST, P.TEXTO, P.DATA_HORA, U.NOME_USUARIO 
 FROM POSTAGENS AS P
 JOIN USUARIOS AS U
 ON P.USUARIO = U.ID_USUARIO;
 
 #5
 SELECT U.NOME_USUARIO, COUNT(P.ID_POST) AS QNT_POST
 FROM USUARIOS AS U
 JOIN POSTAGENS AS P
 ON U.ID_USUARIO = P.USUARIO
 GROUP BY U.ID_USUARIO;
 
 #6
 SELECT U.NOME_USUARIO AS COMENTARAM_2024
 FROM USUARIOS AS U
 JOIN COMENTARIOS AS C
 ON U.ID_USUARIO = C.USUARIO
 WHERE YEAR(C.DATAHORA) = 2024;
 
 #7
 SELECT * FROM GRUPOS
 ORDER BY NOME_GRUPO ASC;
 
 #8
 SELECT *
 FROM GRUPOS
 WHERE DESCRICAO LIKE '%TECNOLOGIA%';
 
 #9
 SELECT C.ID_COMENTARIO, C.TEXTO, C.DATAHORA, U.NOME_USUARIO,C.POST
 FROM COMENTARIOS AS C
 JOIN USUARIOS AS U
 ON C.USUARIO = U.ID_USUARIO;
 
 #10
 SELECT POST, COUNT(ID_COMENTARIO)
 FROM COMENTARIOS
 GROUP BY POST;
 
 #11
 SELECT U.NOME_USUARIO, COUNT(S.SEGUIDOR) AS QNT_SEGUIDORES
 FROM SEGUIDORES_USUARIOS AS S
 JOIN USUARIOS AS U
 ON S.USUARIO = U.ID_USUARIO
 GROUP BY USUARIO;
 
 #12


 #12+1
 SELECT CONCAT_WS(' ',U.NOME_USUARIO, U.SOBRENOME) AS USUARIO,
 MAX(P.DATA_HORA) AS ULTIMO_POST
 FROM USUARIOS AS U
 LEFT JOIN POSTAGENS AS P
 ON U.ID_USUARIO = P.USUARIO
 GROUP BY USUARIO;
 
